In [17]:
import numpy as np

In [18]:
a=np.array([1,2,3])

In [19]:
b=(a+2)

In [20]:
print(b)

[3 4 5]


In [21]:
c=a*5

In [22]:
print(c)

[ 5 10 15]


In [23]:
d=np.sqrt((c))

In [24]:
print(d)

[2.23606798 3.16227766 3.87298335]
