In [5]:
import numpy as np
a=np.arange(1,10).reshape((3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.ndim)
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]],
                     [[13, 14, 15], [16, 17, 18]]])
print(array_3d.ndim)
print(array_3d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
3
(3, 2, 3)


In [14]:
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]
